module;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation-unknown-command"
#pragma clang diagnostic ignored "-Wdocumentation-deprecated-sync"
#pragma clang diagnostic ignored "-Wcast-function-type-strict"
#pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
#pragma clang diagnostic ignored "-Wsign-conversion"
#pragma clang diagnostic ignored "-Wheader-hygiene"
#pragma clang diagnostic ignored "-Wold-style-cast"
#pragma clang diagnostic ignored "-Wdocumentation"
#pragma clang diagnostic ignored "-Wcast-qual"
#pragma clang diagnostic ignored "-Wundef"
// There's Ruby 2.6.0 on macOS, whereas it's
// latest ruby versions on the other platforms,
// and defined structures may have different
// fields
#ifdef __APPLE__
#	include <Ruby/ruby.h>
#   define RESERVED {nullptr}
#else
#	include <ruby.h>
#   define RESERVED nullptr, {nullptr}
#endif
#pragma clang diagnostic pop

#define LOG(state) \
	if (state != 0) [[unlikely]] \
	{ \
		const auto err{rb_errinfo()}; \
		rb_set_errinfo(Qnil); \
		auto string{rb_obj_as_string(err)}; \
		return StringValueCStr(string); \
	}

#define RETOUT(path) \
{ \
	std::fstream output{path, std::fstream::in}; \
	if (!output.is_open()) [[unlikely]] \
		return std::string{}; \
	std::string contents{}; \
	while (!output.eof()) \
	{ \
		std::string line{}; \
		std::getline(output, line); \
		contents += line + '\n'; \
	} \
	std::filesystem::remove(path); \
	return contents; \
}

module ScriptEngine;

import disxx.loader.macho.Loader;
import disxx.disasm.Disassembler;

namespace
{
	rb_data_type_t loader
	{
		"Disxx::Loader",
		{
			nullptr,
			[](void *ptr) -> void { delete static_cast<disxx::loader::macho::Loader *>(ptr); },
			[](const void *) -> std::size_t { return 0z; },
			RESERVED
		},
		nullptr,
		nullptr,
		RUBY_TYPED_FREE_IMMEDIATELY
	};

	rb_data_type_t executable
	{
		"Disxx::ExecutableFile",
		{
			nullptr,
			[](void *ptr) -> void { delete static_cast<disxx::loader::executable::ExecutableFile *>(ptr); },
			[](const void *) -> std::size_t { return 0z; },
			RESERVED
		},
		nullptr,
		nullptr,
		RUBY_TYPED_FREE_IMMEDIATELY
	};

	rb_data_type_t section
	{
		"Disxx::Section",
		{
			nullptr,
			[](void *ptr) -> void { delete static_cast<disxx::loader::executable::Section *>(ptr); },
			[](const void *) -> std::size_t { return 0z; },
			RESERVED
		},
		nullptr,
		nullptr,
		RUBY_TYPED_FREE_IMMEDIATELY
	};

	rb_data_type_t label
	{
		"Disxx::Label",
		{
			nullptr,
			[](void *ptr) -> void { delete static_cast<disxx::loader::executable::Label *>(ptr); },
			[](const void *) -> std::size_t { return 0z; },
			RESERVED
		},
		nullptr,
		nullptr,
		RUBY_TYPED_FREE_IMMEDIATELY
	};

	template <typename T>
	inline T *unwrap(VALUE) noexcept
	{ return nullptr; }

	template <>
	inline disxx::loader::macho::Loader *unwrap<disxx::loader::macho::Loader>(VALUE val) noexcept
	{
		disxx::loader::macho::Loader *ptr{nullptr};
		TypedData_Get_Struct(val, disxx::loader::macho::Loader, &loader, ptr);
		return ptr;
	}

	template <>
	inline disxx::loader::executable::ExecutableFile *unwrap<disxx::loader::executable::ExecutableFile>(VALUE val) noexcept
	{
		disxx::loader::executable::ExecutableFile *ptr{nullptr};
		TypedData_Get_Struct(val, disxx::loader::executable::ExecutableFile, &executable, ptr);
		return ptr;
	}

	template <>
	inline disxx::loader::executable::Section *unwrap<disxx::loader::executable::Section>(VALUE val) noexcept
	{
		disxx::loader::executable::Section *ptr{nullptr};
		TypedData_Get_Struct(val, disxx::loader::executable::Section, &section, ptr);
		return ptr;
	}

	template <>
	inline disxx::loader::executable::Label *unwrap<disxx::loader::executable::Label>(VALUE val) noexcept
	{
		disxx::loader::executable::Label *ptr{nullptr};
		TypedData_Get_Struct(val, disxx::loader::executable::Label, &label, ptr);
		return ptr;
	}
}  /* */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wexit-time-destructors"
#pragma clang diagnostic ignored "-Wglobal-constructors"
const std::filesystem::path ScriptEngine::s_Path
{
	std::filesystem::temp_directory_path()
		/ std::filesystem::path{"io.github.ul71m47um.disxx"}
		/ std::filesystem::path{"ruby-output.dat"}
};

const std::string ScriptEngine::s_Script
{
	std::format
	(
		"# Automatically generated by dis++ - do not edit.\n"
		"class DisxxIO\n"
		"\tdef write(str)\n"
		"\t\tFile.open(\"{}\", \'a\') do |file|\n"
		"\t\t\tfile.write str\n"
		"\t\tend\n"
		"\tend\n"
		"end\n\n"
		"io = DisxxIO::new\n"
		"$stdout = $stderr = io\n\n"
		"# User\'s code begins",
		ScriptEngine::s_Path.string()
	)
};
#pragma clang diagnostic pop

ScriptEngine::ScriptEngine(void) noexcept
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
	: m_Disxx{Qnil}
	, m_Loader{Qnil}
	, m_ExecutableFile{Qnil}
	, m_Section{Qnil}
	, m_Label{Qnil}
	, m_Disassembler{Qnil}
	#pragma clang diagnostic pop
{
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wunknown-warning-option"
	#pragma clang diagnostic ignored "-Wunsafe-buffer-usage-in-format-attr-call"
	#pragma clang diagnostic ignored "-Wcompound-token-split-by-macro"
	#pragma clang diagnostic ignored "-Wcast-function-type-strict"
	#pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
	this->m_Disxx = rb_define_module("Disxx");

	// Ruby classes defenition
	this->m_Loader = rb_define_class_under
	(
		this->m_Disxx,
		"Loader",
		rb_cObject
	);
	this->m_ExecutableFile = rb_define_class_under
	(
		this->m_Disxx,
		"ExecutableFile",
		rb_cObject
	);
	this->m_Section = rb_define_class_under
	(
		this->m_Disxx,
		"Section",
		rb_cObject
	);
	this->m_Label = rb_define_class_under
	(
		this->m_Disxx,
		"Label",
		rb_cObject
	);

	rb_define_alloc_func
	(
		this->m_Loader,
		+[](VALUE val) -> VALUE
		{
			return TypedData_Wrap_Struct
			(
				val,
				&loader,
				new disxx::loader::macho::Loader{}
			);
		}
	);
	rb_define_method
	(
		this->m_Loader,
		"loadFile",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self, VALUE path) -> VALUE
			{
				if (const auto result{unwrap<disxx::loader::macho::Loader>(self)->LoadFile(StringValueCStr(path))}; !result) [[unlikely]]
				{
					rb_raise
					(
						rb_eRuntimeError,
						"%s",
						std::visit
						(
							[](auto &&err) -> const char * { return err.what(); },
							result.error()
						)
					);

					return Qnil;
				}
					
				return self;
			}
		),
		1
	);
	rb_define_method
	(
		this->m_Loader,
		"loadData",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				const auto result{unwrap<disxx::loader::macho::Loader>(self)->LoadData()};
				if (!result) [[unlikely]]
				{
					rb_raise
					(
						rb_eRuntimeError,
						"%s",
						std::visit
						(
							[](auto &&err) -> const char * { return err.what(); },
							result.error()
						)
					);

					return Qnil;
				}

				return TypedData_Wrap_Struct
				(
					rb_const_get
					(
						rb_const_get(rb_cObject, rb_intern("Disxx")),
						rb_intern("ExecutableFile")
					),
					&executable,
					new disxx::loader::executable::ExecutableFile{*result}
				);
			}
		),
		0
	);

	rb_define_alloc_func
	(
		this->m_ExecutableFile,
		+[](VALUE val) -> VALUE
		{
			return TypedData_Wrap_Struct
			(
				val,
				&executable,
				new disxx::loader::executable::ExecutableFile{}
			);
		}
	);
	rb_define_method
	(
		this->m_ExecutableFile,
		"sections",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				auto arr{rb_ary_new()};
				for (auto &var : unwrap<disxx::loader::executable::ExecutableFile>(self)->GetSections())
				{
					rb_ary_push
					(
						arr,
						TypedData_Wrap_Struct
						(
							rb_const_get
							(
								rb_const_get(rb_cObject, rb_intern("Disxx")),
								rb_intern("Section")
							),
							&section,
							new disxx::loader::executable::Section{var}
						)
					);
				}

				return arr;
			}
		),
		0
	);
	rb_define_method
	(
		this->m_ExecutableFile,
		"magic",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return UINT2NUM
				(
					unwrap<disxx::loader::executable::ExecutableFile>(self)
						->GetMagic()
				);
			}
		),
		0
	);

	rb_define_alloc_func
	(
		this->m_Section,
		+[](VALUE val) -> VALUE
		{
			return TypedData_Wrap_Struct
			(
				val,
				&section,
				new disxx::loader::executable::Section{}
			);
		}
	);
	rb_define_method
	(
		this->m_Section,
		"name",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return rb_str_new_cstr
				(
					unwrap<disxx::loader::executable::Section>(self)
						->GetName()
						.data()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Section,
		"labels",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				auto arr{rb_ary_new()};
				for (auto &var : unwrap<disxx::loader::executable::Section>(self)->GetLabels())
				{
					rb_ary_push
					(
						arr,
						TypedData_Wrap_Struct
						(
							rb_const_get
							(
								rb_const_get(rb_cObject, rb_intern("Disxx")),
								rb_intern("Label")
							),
							&label,
							new disxx::loader::executable::Label{var}
						)
					);
				}

				return arr;
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Section,
		"address",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return ULL2NUM
				(
					unwrap<disxx::loader::executable::Section>(self)
						->GetAddress()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Section,
		"offset",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return ULL2NUM
				(
					unwrap<disxx::loader::executable::Section>(self)
						->GetOffset()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Section,
		"index",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return USHORT2NUM
				(
					unwrap<disxx::loader::executable::Section>(self)
						->GetIndex()
				);
			}
		),
		0
	);

	rb_define_alloc_func
	(
		this->m_Label,
		+[](VALUE val) -> VALUE
		{
			return TypedData_Wrap_Struct
			(
				val,
				&label,
				new disxx::loader::executable::Label{}
			);
		}
	);
	rb_define_method
	(
		this->m_Label,
		"name",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return rb_str_new_cstr
				(
					unwrap<disxx::loader::executable::Label>(self)
						->GetName()
						.data()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Label,
		"address",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return ULL2NUM
				(
					unwrap<disxx::loader::executable::Label>(self)
						->GetAddress()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Label,
		"offset",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return ULL2NUM
				(
					unwrap<disxx::loader::executable::Label>(self)
						->GetOffset()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Label,
		"size",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				return ULL2NUM
				(
					unwrap<disxx::loader::executable::Label>(self)
						->GetSize()
				);
			}
		),
		0
	);
	rb_define_method
	(
		this->m_Label,
		"data",
		RUBY_METHOD_FUNC
		(
			+[](VALUE self) -> VALUE
			{
				auto arr{rb_ary_new()};
				for (const auto byte : unwrap<disxx::loader::executable::Label>(self)->GetData<std::uint8_t>())
					rb_ary_push(arr, LONG2FIX(byte));
				return arr;
			}
		),
		0
	);
	#pragma clang diagnostic pop
}

ScriptEngine::ScriptEngine(const ScriptEngine &other) noexcept
	: m_Disxx{other.m_Disxx}
	, m_Loader{other.m_Loader}
	, m_ExecutableFile{other.m_ExecutableFile}
	, m_Section{other.m_Section}
	, m_Label{other.m_Label}
	, m_Disassembler{other.m_Disassembler}
{}

ScriptEngine &ScriptEngine::operator=(const ScriptEngine &other) noexcept
{
	if (this != &other) [[likely]]
	{
		this->m_Disxx = other.m_Disxx;
		this->m_Loader = other.m_Loader;
		this->m_ExecutableFile = other.m_ExecutableFile;
		this->m_Section = other.m_Section;
		this->m_Label = other.m_Label;
		this->m_Disassembler = other.m_Disassembler;
	}

	return *this;
}

ScriptEngine::ScriptEngine(ScriptEngine &&other) noexcept
	: m_Disxx{std::move(other.m_Disxx)}
	, m_Loader{std::move(other.m_Loader)}
	, m_ExecutableFile{std::move(other.m_ExecutableFile)}
	, m_Section{std::move(other.m_Section)}
	, m_Label{std::move(other.m_Label)}
	, m_Disassembler{std::move(other.m_Disassembler)}
{}

ScriptEngine &ScriptEngine::operator=(ScriptEngine &&other) noexcept
{
	if (this != &other) [[likely]]
	{
		this->m_Disxx = std::move(other.m_Disxx);
		this->m_Loader = std::move(other.m_Loader);
		this->m_ExecutableFile = std::move(other.m_ExecutableFile);
		this->m_Section = std::move(other.m_Section);
		this->m_Label = std::move(other.m_Label);
		this->m_Disassembler = std::move(other.m_Disassembler);
	}

	return *this;
}

std::string ScriptEngine::ExecFile(const std::filesystem::path &path) noexcept
{
	if (const auto dir{s_Path.parent_path()}; !std::filesystem::exists(dir))
		std::filesystem::create_directory(dir);

	const std::filesystem::path temp
	{
		std::filesystem::temp_directory_path()
			/ std::filesystem::path{"io.github.ul71m47um.disxx"}
			/ std::filesystem::path{"main.rb"}
	};

	std::fstream script
	{
		temp,
		std::fstream::in
			| std::fstream::out
			| std::fstream::binary
			| std::fstream::trunc
	}, file
	{
		path,
		std::fstream::in
	};

	if (!file.is_open() || !script.is_open()) [[unlikely]]
		return std::string{};

	for (const auto ch : s_Script)
		script.write(&ch, sizeof(ch));

	while (!file.eof())
	{
		std::string line{};
		std::getline(file, line);
		line += '\n';
		for (const auto ch : line)
			script.write(&ch, sizeof(ch));
	}

	script.flush();

	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wcompound-token-split-by-macro"
	#pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
	auto state{0};
	rb_load_protect(rb_str_new_cstr(temp.c_str()), 0, &state);
	LOG(state)
	#pragma clang diagnostic pop

	std::filesystem::remove(temp);

	RETOUT(s_Path)
}

std::string ScriptEngine::ExecString(std::string_view str) noexcept
{
	const auto script{std::string{s_Script} + str};

	auto state{0};
	rb_eval_string_protect(script.c_str(), &state);
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
	LOG(state)
	#pragma clang diagnostic pop

	RETOUT(s_Path)
}
